///
/// NitroAesOnLoad.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

package com.margelo.nitro.NitroAes

import android.util.Log

internal class NitroAesOnLoad {
  companion object {
    private const val TAG = "NitroAesOnLoad"
    private var didLoad = false
    /**
     * Initializes the native part of "NitroAes".
     * This method is idempotent and can be called more than once.
     */
    @JvmStatic
    fun initializeNative() {
      if (didLoad) return
      try {
        Log.i(TAG, "Loading NitroAes C++ library...")
        System.loadLibrary("NitroAes")
        Log.i(TAG, "Successfully loaded NitroAes C++ library!")
        didLoad = true
      } catch (e: Error) {
        Log.e(TAG, "Failed to load NitroAes C++ library! Is it properly installed and linked? " +
                    "Is the name correct? (see `CMakeLists.txt`, at `add_library(...)`)", e)
        throw e
      }
    }
  }
}
